server:
  port: 8002
spring:
  application:
    name: micro-weather-eureka-client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/